### ISSUE TITLE
Geolocation broken

### ISSUE THREAD

**Issue by softgrow** [planningalerts-scrapers/burnside#4]
I'm getting alerts for applications via this scraper incorrectly as they are being located in the Foyer of the Westpac building, corner of King William Street and Currie Street Adelaide 5000.

**Comment by softgrow** [comment]
Compare row 637 and 638 of Burnside data

15/5/17	Change of land use (residential to child care centre), demolition of existing dwelling and construction of two storey child care centre, car park and landscaping.	https://www.burnside.sa.gov.au/Development-Applications-on-Notification/Category-3/441-Glynburn-Road-Leabrook	180\0172\17	441 Glynburn Road, Leabrook, SA	26/5/17	mailto:burnside@burnside.sa.gov.au
18/5/17	Construction of three single-storey group dwellings	https://www.burnside.sa.gov.au/Development-Applications/Category-2/103-Sydney-Street-Glenunga	180\0323\17	Development Application, SA	1/6/17	mailto:burnside@burnside.sa.gov.au

There also seems to be another change earlier changing the contact field

11/4/16	Swimming pool including safety fencing, verandah and outbuilding.	http://www.burnside.sa.gov.au/Develop/Planning_Development/Development_Applications_on_Public_Notification/Category_2_Development_Applications/35_Inverness_Avenue_St_Georges	180\0179\16	35 Inverness Avenue, St Georges, SA	22/4/16	http://www.burnside.sa.gov.au/Develop/Planning_Development/Development_Applications_on_Public_Notification/Category_2_Development_Applications/35_Inverness_Avenue_St_Georges
20/4/17	Single storey detached dwelling including incidental cut & fill, retaining and fencing.	https://www.burnside.sa.gov.au/Development-Applications-on-Notification/Category-2/6B-Bennett-Avenue-Beaumont-2	180\1003\16	6B Bennett Avenue, Beaumont, SA	20/4/17	mailto:burnside@burnside.sa.gov.au

Anyway, looks like its selecting the wrong field for location.

**Comment by LoveMyData** [comment]
Looks like council updated their website format. Thanks for reporting and will adjust the scrpaer

**Comment by LoveMyData** [comment]
We've disabled auto-run on this scraper until it's fixed. Remember to turn it back on when it's working!

**Comment by henare** [comment]
Thanks for reporting this @softgrow :ok_hand: and thanks for fixing it @LoveMyData :star2: 

#5 has been merged and I've re-enabled auto-run :rocket:
